#!/usr/bin/with-contenv bash

while [ ! -f /tmp/state/10-nodejs-init ]
do
  sleep 1
done

if [ ! -f /tmp/state/10-nodejs ]; then



  echo 'Initialization Complete' >/tmp/state/10-nodejs
fi

echo ''
echo '** [formio-api] Starting nodeJS'
cd /app
exec s6-setuidgid nodejs node main.js
