#!/usr/bin/with-contenv bash

for s in /assets/functions/*; do source $s; done
PROCESS_NAME="formio-api"

check_container_initialized
check_service_initialized init
if [ ! -z ${DB_USER} ] ; then DB_CREDSTRING=$DB_USER'@'; fi;
if [ ! -z ${DB_PASS} ] ; then DB_CREDSTRING=$DB_USER':'$DB_PASS'@'; fi;
export DB_SECRET=${DB_SECRET:-"secret"}
export FORMIO_MANAGER_HOST=${FORMIO_MANAGER_HOST:-"${FORMIO_HOST}"}
export FORMIO_PROTOCOL=${FORMIO_PROTOCOL:-"https"}
if [ '$FORMIO_PROTOCOL' = 'http' ] ; then export FORMIO_PORT=80; else export FORMIO_PORT=443; fi;
export JWT_SECRET=${JWT_SECRET:-"secret"}
export JWT_EXPIRE_TIME=${JWT_EXPIRE_TIME:-"240"}
export PROJECT_TEMPLATE=${PROJECT_TEMPLATE:-"default"}
export USER_FORM=${USER_FORM:-"user"}
export USER_LOGIN_FORM=${USER_LOGIN_FORM:-"admin/login"}
export ROOT_EMAIL=${ROOT_EMAIL:-"admin@example.com"}
export ROOT_PASS=${ROOT_PASS:-"password"}
export MONGO=${DB_STRING:-'mongodb://'$DB_CRED_STRING$DB_HOST':'$DB_PORT'/'$PROJECT_TEMPLATE}
liftoff

print_info "Starting Formio API ${FORMIO_VERSION}"
cd /app
exec sudo -E -u nodejs HOME=/app npm start