#!/usr/bin/with-contenv bash

### Set Defaults
    API_URL=${API_URL:-"127.0.0.1"}
    APP_URL=${VIRTUAL_HOST:-"127.0.0.1"}
    REVERSE_PROXY=${REVERSE_PROXY:-"true"}
    APP=${APP:-"basic"}

    if [ "$REVERSE_PROXY" = "true" ] || [ "$REVERSE_PROXY" = "TRUE" ];  then
        URL_PREFIX=https://
    else
        URL_PREFIX=http://
    fi
    

### Check if installed
    chown -R nodejs:nodejs /app
    if [ ! -f "/app/package.json" ]; then
        echo '** [formio-app] No Data Found, Creating Fresh Install'
        apt-get update
        apt-get install -y \
            git \
            g++ \
            make
        
### Install App based on Selection
       case "$APP" in
            "basic" | "BASIC"  )
                sudo -u nodejs git clone https://github.com/formio/formio-app-basic /app
                cd /app
                sudo -u nodejs npm install
                # Gulp Fix
                sudo -u nodejs npm install karma@latest
                jsontmp=$(mktemp)
                jq '.resolutions .angular="1.6.7"' /app/bower.json >"$jsontmp" && mv "$jsontmp" /app/bower.json
                chown -R nodejs:nodejs /app/bower.json
                sudo -u nodejs bower install
            ;;
            "eventmanager" | "EVENTMANAGER" | "events"  )
                sudo -u nodejs git clone https://github.com/formio/formio-app-eventmanager /app
                cd /app
                sudo -u nodejs npm install
                # Gulp Fix
                sudo -u nodejs npm install karma@latest
                jsontmp=$(mktemp)
                jq '.resolutions .angular="1.6.7"' /app/bower.json >"$jsontmp" && mv "$jsontmp" /app/bower.json
                chown -R nodejs:nodejs /app/bower.json
                sudo -u nodejs bower install
            ;;
            "formbuilder" | "FORMBUILDER" | "builder"  )
                sudo -u nodejs git clone https://github.com/formio/formio-app-formbuilder /app
                cd /app
                sudo -u nodejs npm install
                # Gulp Fix
                sudo -u nodejs npm install karma@latest
                sudo -u nodejs bower install
            ;;
            "formio" | "FORMIO" | "frontend" | "main"  )
                sudo -u nodejs git clone https://github.com/formio/formio-app-formio /app
                cd /app
                sudo -u nodejs npm install
                # Gulp Fix
                sudo -u nodejs npm install karma@latest
                jsontmp=$(mktemp)
                jq '.dependencies .angular="1.6.7"' /app/bower.json >"$jsontmp" && mv "$jsontmp" /app/bower.json
                chown -R nodejs:nodejs /app/bower.json
                sudo -u nodejs bower install
            ;;
            "gpstracker" | "GPSTRACKER" | "gps" | "main"  )
                sudo -u nodejs git clone https://github.com/formio/formio-app-gpstracker /app
                cd /app
                sudo -u nodejs npm install
                # Gulp Fix
                sudo -u nodejs npm install karma@latest
                jsontmp=$(mktemp)
                jq '.dependencies .angular-bootstrap="2.5.0"' /app/bower.json >"$jsontmp" && mv "$jsontmp" /app/bower.json
                chown -R nodejs:nodejs /app/bower.json
                sudo -u nodejs bower install
            ;;
            "humanresources" | "HUMANRESOURCES" | "hr" | "HR"  )
                sudo -u nodejs git clone https://github.com/formio/formio-app-humanresources /app
                cd /app
                sudo -u nodejs npm install
                # Gulp Fix
                sudo -u nodejs npm install karma@latest
                jsontmp=$(mktemp)
                jq '.resolutions .angular="1.6.7"' /app/bower.json >"$jsontmp" && mv "$jsontmp" /app/bower.json
                chown -R nodejs:nodejs /app/bower.json
                sudo -u nodejs bower install
            ;;
            "movie" | "MOVIE"  )
                sudo -u nodejs git clone https://github.com/formio/formio-app-movie /app
                cd /app
                sudo -u nodejs npm install
                # Gulp Fix
                sudo -u nodejs npm install karma@latest
                jsontmp=$(mktemp)
                jq '.dependencies .angular="1.6.7"' /app/bower.json >"$jsontmp" && mv "$jsontmp" /app/bower.json
                jq '.dependencies .bootswatch="v3.3.6+2"' /app/bower.json >"$jsontmp" && mv "$jsontmp" /app/bower.json
                chown -R nodejs:nodejs /app/bower.json
                sudo -u nodejs bower install
            ;;
            "prizedrawing" | "PRIZEDRAWING"  )
                sudo -u nodejs git clone https://github.com/formio/formio-app-prizedrawing /app
                cd /app
                sudo -u nodejs npm install
                # Gulp Fix
                sudo -u nodejs npm install karma@latest
                sudo -u nodejs bower install
            ;;
            "salesquote" | "SALESQUOTE" | "sales"  )
                sudo -u nodejs git clone https://github.com/formio/formio-app-salesquote /app
                cd /app
                sudo -u nodejs npm install
              # Gulp Fix
                sudo -u nodejs npm install karma@latest
                sudo -u nodejs bower install
            ;;
            "servicetracker" | "SERVICETRACKER" | "service"  )
                sudo -u nodejs git clone https://github.com/formio/formio-app-servicetracker /app
                cd /app
                sudo -u nodejs npm install
              # Gulp Fix
                sudo -u nodejs npm install karma@latest
                jsontmp=$(mktemp)
                jq '.resolutions .angular="1.6.7"' /app/bower.json >"$jsontmp" && mv "$jsontmp" /app/bower.json
                chown -R nodejs:nodejs /app/bower.json
                sudo -u nodejs bower install    
            ;;
            "todo" | "TODO"  )
                sudo -u nodejs git clone https://github.com/formio/formio-app-todo /app
                cd /app
                sudo -u nodejs npm install
                # Gulp Fix
                sudo -u nodejs npm install karma@latest
                jsontmp=$(mktemp)
                jq '.resolutions .angular="1.6.7"' /app/bower.json >"$jsontmp" && mv "$jsontmp" /app/bower.json
                chown -R nodejs:nodejs /app/bower.json
                sudo -u nodejs bower install
            ;;
        esac

        apt-get purge -y \
                git \
                g++ \
                make
        apt-get -y autoremove 
        apt-get clean 
        rm -rf /var/lib/apt/lists/*
    fi

### Change URLs
sed -i "/var APP_URL = /c\var APP_URL = '$URL_PREFIX$APP_URL';" /app/dist/config.js
sed -i "/var API_URL = /c\var API_URL = '$URL_PREFIX$API_URL';" /app/dist/config.js

    
mkdir -p /tmp/state
touch /tmp/state/10-app-init
