#!/usr/bin/with-contenv bash

while [ ! -f /tmp/state/20-nodejs-init ]
do
  sleep 1
done

if [ ! -f /tmp/state/20-nodejs ]; then



  echo 'Initialization Complete' >/tmp/state/10-nodejs
fi

echo ''
echo '** Starting NodeJS'
cd /app
exec node main.js
