#!/usr/bin/with-contenv bash

while [ ! -f /tmp/state/99-container-init ]
do
  sleep 1
done

if [ ! -f /tmp/state/10-nginx ]; then

	### Check to see if this is a new install, if yes create directories...

	### Force Reset Permissions for Security
	mkdir -p /var/log/nginx/
	chown -R nginx /var/log/nginx/
	mkdir -p /www/logs/nginx
	mkdir -p /tmp/nginx
	chown -R nginx /www/logs/nginx
	chown nginx /tmp/nginx
	echo 'Initialization Complete' >/tmp/state/10-nginx
fi

echo ''
echo '** Starting nginx..'
exec nginx
