#!/usr/bin/with-contenv bash

while [ ! -f /tmp/state/10-nodejs-init ]
do
  sleep 1
done

if [ ! -f /tmp/state/10-nodejs ]; then



  echo 'Initialization Complete' >/tmp/state/10-haraka
fi

echo ''
echo '** Starting NodeJS'
cd /app
#exec npm run version && node main.js
#npm run-script start nodemon main.js
exec node main.js
